### ISSUE TITLE
Receiving/Inserting date (Possible issue:Timezone displaying one day ahead)

### ISSUE THREAD

**Issue by Sabatr** [SE701ProjectGroup4/git-brunching#148]
**Describe the bug**
When receiving the date from the API (endpoint: /reservation/{reservationID}), the date received is the previous to the day inserted. 

**To Reproduce**
1. Create a booking for KFC with X date
2. Copy the reference ID
3. Go to the edit ID in the edit booking
4. The date there will be a day previous to the one you entered

**Expected behavior**
The dates are the same.

**Comment by MingChen91** [comment]
@Sabatr This is happening because we initially designed the database to have date and time to be in two separate columns instead of a date-time column. 
So if you get the date of 2020-03-18, it assumes its 2020-03-18 00:00:00 (NZT) , which then gets auto converted to UTC, which is 2020-03-17T11:00:00.000Z so it shows as its one day before. 

Depending on what you need it to do I think you can convert it to display as a local time. Lemme know if this is what you're asking

example script
![image](https://user-images.githubusercontent.com/48301693/77129250-283f8680-6ab8-11ea-8c37-8778c5b533f9.png)

**Comment by George-E-M** [comment]
Date-fns (the current date library we use) has a few methods that can be used to convert between time zones, see [here.](https://date-fns.org/v2.0.0-alpha.27/docs/Time-Zones)

**Comment by MingChen91** [comment]
Proposed solutions:

-  Change the database to use 1 column with date-time format
-  Process the date either in the back end and just send it as a string(yyyy-mm-dd), or frontend to convert to local time and then truncate.
