### ISSUE TITLE
Manually entering date

### ISSUE THREAD

**Issue by Sabatr** [SE701ProjectGroup4/git-brunching#155]
**Describe the bug**
When selecting the date, if a user tries to type in the date the app crashes

**To Reproduce**
1. Go to KFC
2. Click on the date textfield
3. Delete a character
4. The app will break

**Expected behavior**
The app doesn't break and users are allowed to manually type their desired date

**Screenshots**

**Additional context**

**Comment by George-E-M** [comment]
This seems to happen because the onChange function calls format() on the value in the textfield everytime it changes. And if it doesn't match the expected format (yyyy-MM-dd) then it throws the exception/crashes.

The easiest fix would probably be to disable writing to the text field. To do this you have to override the Textfield component of the KeyboardDatePicker. Example is below.

```javascript
const TextFieldComponent = (props) => {
  return <TextField {...props} disabled={true} />
}
...
return (
...
   <KeyboardDatePicker
     ...
     TextFieldComponent={TextFieldComponent}
   />
```
