### ISSUE TITLE
Fix Edit booking function

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/git-brunching#189]
**Describe the bug**
Currently when entering the booking ID of one of the pre-existing bookings into the Id field that pops up when pressing the edit booking button on the landing page, a warning will appear detailing that an error has occurred, and the user will not be able to edit the booking.

**To Reproduce**
1. Go to /Restaurant to view the existing bookings
2.Copy the id of one of the bookings
3. Go back to the landing page and press Edit booking
4. Paste in the booking ID
5. Press confirm

**Expected behavior**
Upon entering the valid booking ID and pressing confirm, a page should appear, allowing the user to edit the details of the inputted booking. All existing booking references should accessible through this method and should not return an error.

**Comment by WilbertGui** [comment]
LGFM

**Comment by gargi-bansal** [comment]
Not sure if this is a bug. The edit booking throws an error because it queries the database and the reservation does not exist in the database (it is mock data hardcoded into the BookingEditPopupDialog component). If I add a reservation directly in the database and then try edit the booking from the front end, I am able to view my booking details.

**Comment by mitchfaulcon** [comment]
Yea I don't think this is a problem anymore. @NathanMills1 if you want to double check
